source /usr/share/defaults/etc/profile

alias bureau="cd /home/adrient/Bureau";

alias info="cd /home/adrient/Documents/informatique";
alias cherche="eopkg sr";
alias gg="gedit ~/.bashrc";
alias ll="ls -lhc";
alias lla="ls -lahc";
alias info="cd ~/Documents/info";
alias kk="cd ~/gitkraken/ && ./gitkraken"
